name: Linter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Upgrade Yarn
        run: |
          corepack enable
          yarn set version stable

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - run: yarn lint
